// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMXbrPHr52O_aSJcNrINcQQrHqoXwT4G8',
    appId: '1:616192795330:web:467ec9c1bb7f552580d15b',
    messagingSenderId: '616192795330',
    projectId: 'kopi-nang',
    authDomain: 'kopi-nang.firebaseapp.com',
    storageBucket: 'kopi-nang.firebasestorage.app',
    measurementId: 'G-P4S9ZHG0D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFEkII9yEKL2TcxXJXwnIOE9JGkmp8fKc',
    appId: '1:616192795330:android:f6afab9126a2820e80d15b',
    messagingSenderId: '616192795330',
    projectId: 'kopi-nang',
    storageBucket: 'kopi-nang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPVL2wKddjMXFOYLn3z_jxpVQ02_6ULY',
    appId: '1:616192795330:ios:399248a1223c118e80d15b',
    messagingSenderId: '616192795330',
    projectId: 'kopi-nang',
    storageBucket: 'kopi-nang.firebasestorage.app',
    iosClientId: '616192795330-qh3v3u54rq0eqgo3idj7dpjvgv8diul6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kopinang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEPVL2wKddjMXFOYLn3z_jxpVQ02_6ULY',
    appId: '1:616192795330:ios:399248a1223c118e80d15b',
    messagingSenderId: '616192795330',
    projectId: 'kopi-nang',
    storageBucket: 'kopi-nang.firebasestorage.app',
    iosClientId: '616192795330-qh3v3u54rq0eqgo3idj7dpjvgv8diul6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kopinang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMXbrPHr52O_aSJcNrINcQQrHqoXwT4G8',
    appId: '1:616192795330:web:37d0d22c71fbde9680d15b',
    messagingSenderId: '616192795330',
    projectId: 'kopi-nang',
    authDomain: 'kopi-nang.firebaseapp.com',
    storageBucket: 'kopi-nang.firebasestorage.app',
    measurementId: 'G-RC6FMG7RWZ',
  );

}